apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  # Headless service.
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
